name: dio
description: A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation, File Downloading, Timeout etc.
version: 3.1.0
homepage: https://github.com/flutterchina/dio

environment:
  sdk: '>2.4.0 <3.0.0'

dependencies:
  http_parser: ">=0.0.1 <5.0.0"
  path: ^1.6.4
  meta: '>=1.4.0 <1.7.0'

dev_dependencies:
  test: ^1.5.1
  pedantic: ^1.8.0

