name: json_serializable_3_5_2
version: 5.3.3
description: >-
  Automatically generate code for converting to and from JSON by annotating
  Dart classes.
repository: https://github.com/google/json_serializable.dart
environment:
  sdk: '>=2.11.99 <3.0.0'

dependencies:
  analyzer: ^5.0.0
  build: '>=0.12.6 <3.0.0'
  build_config: '>=0.2.6 <2.0.0'

  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation` properly constrains all features it provides.
  # For v3 only – allow a wide range since the only change was to REMOVE things
  # from json_annotation
  json_annotation_3_1_1:
    hosted:
      name: json_annotation_3_1_1
      url: https://pub.workiva.org
    version: ^5.3.0 # This version doesn't matter, there's only the 3_1_1 forked version
  meta: ^1.1.0
  path: ^1.3.2
  source_gen: '>=0.9.6 <2.0.0'

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^2.0.0
  collection: ^1.14.0
  dart_style: '>=1.0.0 <3.0.0'
  logging: ^1.0.0
  pub_semver: ^2.0.0
  source_gen_test:
    path: ../source_gen_test-1.0.5
  test: ^1.6.0
  yaml: ^3.0.0
