name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - _integration/**/*
      - test_consume_workiva/**
    tags:
      - "**"

permissions:
  contents: read
  id-token: write

jobs:
    build-image:
        name: Build Image
        runs-on: [self-hosted, xl, al2023]
        steps:
            - uses: actions/checkout@v4
            - uses: Workiva/gha-setup-credentials@v2.0.1
            - name: Build Image
              run: docker build . --file Dockerfile --tag w_dio
            - name: Publish Image
              uses: Workiva/gha-docker-push@v3.0.0
              with:
                local-tag: w_dio


