name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - _integration/**/*
      - test_consume_workiva/**
    tags:
      - "**"

permissions:
  contents: read
  id-token: write

jobs:
    build-image:
        name: Build Image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dart-lang/setup-dart@v1.6.2
            - name: Install tools
              run: |
                  sudo apt-get update -qq && \
                  sudo apt-get dist-upgrade -y && \
                  sudo apt-get install -y jq && \
                  sudo apt-get autoremove -y && \
                  sudo apt-get clean all


