name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - _integration/**/*
      - test_consume_workiva/**
    tags:
      - "**"

permissions:
  contents: read
  id-token: write

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [2.18.7, 2.19.6]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1.6.2
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install tools
        run: |
          sudo apt-get update -qq && \
          sudo apt-get dist-upgrade -y && \
          sudo apt-get install -y jq && \
          sudo apt-get autoremove -y && \
          sudo apt-get clean all

      - name: Install dependencies
        run: |
          pwd
          ls -alsh
          cd dio
          dart pub get
          cd ..
      - name: Make directory
        run: |
          mkdir pub_temp
      - name: Generate tarball
        run: |
          cp dio/CHANGELOG.md pub_temp/
          cp dio/LICENSE pub_temp/
          cp dio/README.md pub_temp/
          cp dio/analysis_options.yaml pub_temp/
          cp dio/pubspec.yaml pub_temp/
          echo "tar czf pub_package.pub.tgz"
          tar czf pub_package.pub.tgz -C pub_temp .
          rm -rf pub_temp
