name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - _integration/**/*
      - test_consume_workiva/**
    tags:
      - "**"

permissions:
  contents: read
  id-token: write

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [2.18.7, 2.19.6]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1.6.2
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install tools
        run: |
          sudo apt-get update -qq && \
          sudo apt-get dist-upgrade -y && \
          sudo apt-get install -y jq && \
          sudo apt-get autoremove -y && \
          sudo apt-get clean all

      - name: Install dependencies
        run: |
          cd dio
          dart pub get
          cd ..
      - name: Make directory for dio
        run: mkdir pub_temp
      - name: Generate tarball for dio
        run: |
          cp -r dio/CHANGELOG.md pub_temp/
          cp -r dio/LICENSE pub_temp/
          cp -r dio/lib pub_temp/
          cp -r dio/README.md pub_temp/
          cp -r dio/analysis_options.yaml pub_temp/
          cp -r dio/pubspec.yaml pub_temp/
          echo "tar czf pub_package.pub.tgz"
          tar czf pub_package.pub.tgz -C pub_temp .

      - name: Install dependencies
        run: |
          cd json_annotation-3.1.1
          dart pub get
          cd ..
      - name: Make directory for json_annotation
        run: mkdir json_annotation
      - name: Generate tarball for json_annotation
        run: |
          cp -r json_annotation-3.1.1/CHANGELOG.md json_annotation/
          cp -r json_annotation-3.1.1/LICENSE json_annotation/
          cp -r json_annotation-3.1.1/lib json_annotation/
          cp -r json_annotation-3.1.1/README.md json_annotation/
          cp -r json_annotation-3.1.1/pubspec.yaml json_annotation/
          echo "tar czf pub_package.pub.tgz"
          tar czf pub_package.pub.tgz -C json_annotation .

      - name: Make directory for json_serializable
        run: mkdir json_serializable
      - name: Generate tarball for json_serializable-3.5.2
        run: |
          cp -r json_serializable-3.5.2/example json_serializable/
          cp -r json_serializable-3.5.2/lib json_serializable/
          cp -r json_serializable-3.5.2/CHANGELOG.md json_serializable/
          cp -r json_serializable-3.5.2/LICENSE json_serializable/
          cp -r json_serializable-3.5.2/lib json_serializable/
          cp -r json_serializable-3.5.2/README.md json_serializable/
          cp -r json_serializable-3.5.2/build.yaml json_serializable/
          cp -r json_serializable-3.5.2/pubspec.yaml json_serializable/
          echo "tar czf pub_package.pub.tgz"
          tar czf pub_package.pub.tgz -C json_serializable .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: pub_temp/*

