name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - _integration/**/*
      - test_consume_workiva/**
    tags:
      - "**"

permissions:
  contents: read
  id-token: write

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [2.18.7, 2.19.6]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1.6.2
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install tools
        run: |
          sudo apt-get update -qq && \
          sudo apt-get dist-upgrade -y && \
          sudo apt-get install -y jq && \
          sudo apt-get autoremove -y && \
          sudo apt-get clean all

      - name: Install dependencies
        run: |
          cd dio
          dart pub get
          cd ..
      - name: Make directory
        run: mkdir dio
      - name: Generate tarball
        run: |
          cp dio/CHANGELOG.md dio/
          cp dio/LICENSE dio/
          cp dio/lib dio/
          cp dio/README.md dio/
          cp dio/analysis_options.yaml dio/
          cp dio/pubspec.yaml dio/
          echo "tar czf pub_package.pub.tgz"
          tar czf pub_package.pub.tgz -C dio .
          rm -rf dio
      - name: Install dependencies
        run: |
          cd json_annotation-3.1.1
          dart pub get
          cd ..
      - name: Make directory
        run: mkdir json_annotation-3.1.1
      - name: Generate tarball for json_annotation-3.1.1
        run: |
          cp json_annotation-3.1.1/CHANGELOG.md json_annotation-3.1.1/
          cp json_annotation-3.1.1/LICENSE json_annotation-3.1.1/
          cp json_annotation-3.1.1/lib json_annotation-3.1.1/
          cp json_annotation-3.1.1/README.md json_annotation-3.1.1/
          cp json_annotation-3.1.1/pubspec.yaml json_annotation-3.1.1/
          echo "tar czf pub_package.pub.tgz"
          tar czf pub_package.pub.tgz -C json_annotation-3.1.1 .
          rm -rf json_annotation-3.1.1

